sonar.projectKey=Devops-Assignment-1
sonar.projectName=Devops-Assignment-1
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=sqp_0e105fd022480ffce5323261729d855ebeb12b83